app:
    alertmanager:
        env: ENC[AES256_GCM,data:X3Yy5WChYjG+pn8aw51A51w1m5YC/93vwRXjCgOnxBNe11L2gGUXyoySj90nuNEVAJQXssgH/2xCW3cWuSqrq7sfCKLFxBadE52CFWVko3lqT5ZQPkFl/1hWBjb7+o8=,iv:vDbQFywzallBfvT9U7QvQNN9/vUoM9AoGGxSvJahuiY=,tag:zDD08stnVvpYvxPSx2QeSw==,type:str]
sops:
    age:
        - recipient: age162k3jv9wyce4dkly60tu0l9jmme5qa3fmcrknrz6lx54ru2ftgaqcsy5e2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBN1NyRVVwL2hTaGV1bHA0
            T1RsQ3NHRTgrRnhHRTBTcjliaWVPa2lZeWlzCmo5WmdQSTkxY2lid3dnejJVSUhp
            blgySWxaNWh3YkdIYTkzY09GTEczR3MKLS0tIEdibVRkaENscm50d1cvUGdQMkxS
            TDVjMmgzaHdHc2tPdCtYMGRzckNYbUEKM4yBvyu1Qhg2mkyxpAZYvV8kUatf3h3R
            qg6cVRByCA2x85KDgVUyndUAXBZLaHbIYbxZTRTi1oRUNxaPgwocbA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10ja28r58wftqjg6ps4vydx6wk5vyqpth8pwzpdcrk889e2hltseqx4af72
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZXUwSzVxWmRVWVY3RitH
            d1BTd3c2bVZqT2YydjRvcTFBMlNWZ0YzVUdZCjgrUW9OVkRtWHc3L1J3YTBERy9G
            M2NGVmdZa0MxYUNKNnNYbzkxMEVJb0UKLS0tIGd0ZEpiSUFtWHFkSHVtU1NFSnk5
            RFJ6TzZFSUgzUFI0elR2ZUdVZWJMcVUKsOnTDQB7M2vkdCyVAwSEa7q3HeO80Wxx
            2o58E4hEXzJCFnKlVW3g2FLkq8le9jqS6NYg3FRS3PpdzNaqqO55nw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xuwlyavt70tt7rc0ufrwh7h907ymvg5mt7amxy0pygafmtm7eses2yj69x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZL3FGa3VGeHF2VDZocXdv
            RUlrdGhqV3BkRWdSOXhBZzdYbzRYckpCdHlvCjkvbXZzU0hkT09nZzNWYTJpUXNP
            VzFIRGsxZHE2ZDhmWU42ai9lNkk1NHMKLS0tIDZjMFQranFxT0Fya0VUcHBBRmF1
            aFVzbGk1SjNvZGpkRzYvdmlKUnkwQ0UKn1VklBYc62XqSQASViT1LQ4P6oGq5cFA
            0bPTCE8jwSv0yWM3reTdcWgww6amUHYfhaqnZTBdXZ7KNO1fKbgNwg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ued9ufgfwkrx00n3vmneae6grex4r0nuuytnwdk63u62flga4u5s9kd20j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwdWlETkVod2l0N0VNdldk
            NEc1T21lQ2R5TkRvcEtscVYyNFRmc1Ztb0NBCmpTOE1nSDgxQ0JLd0lCWmRSaEda
            UExZNS9EYjlHR1R3cWQ2VHNxenI5UkUKLS0tIEhrOVkyWGY4QlN2bWNBb0pmMGta
            U0haK1NJTGVQSEpTYVdsby83blNaUGsKZzpONQf7B206T4xMkIojeVZlV/aikVDR
            MdIftusUXFXYXJJ1xKYurLmqb8MHqvkZuOglwvWrbAH0+p2D1w6THg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1fsd8gpknmdtffnkq8an32zut24gf3h2vmglpaellh0j8fymrefvq25cjc5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMG13WkR3TDQrUDlreHZs
            K000T05DRjYyUmc0dlJyZTAzV3pQVmltTG40CmhobXMzNm5OYUQ0WVJYMENyakxl
            a2hBK2Z1Nm04UmRDUXQ3dlZIdFpTT1EKLS0tIGhYeTNHc29jTzR0NUNkS21ldG45
            QzdDc2tHV1IwdVJSWVpSdThHVWJabW8KmLz8bHJpFoYaA5xNRlAhQCC7ZOANkRVG
            4DojrbmJH0/5Zn4a9VDLtWNUOTawrw9LTZOFnJvjEDfGHTm8hsZvhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T17:29:27Z"
    mac: ENC[AES256_GCM,data:LNnjLj6ghuE7HWQUGY/xA4IVMQEBxDzIkUfNADDVlOKc7Aqnl5h6AC6P5dLn3zlZGGsmLW2YEH+K3BSKMUfNwtRSlNYGJC4fMpscvowcj+jdrr0KRRjaIN0ifLUzjrj13SBG9cJ5cnrb9N2tU+vXjKX+t3p0OWc9nOP7IGiLLP8=,iv:CkWO+yauEOEFr1fjg/wkxxM97sls1Izbyaxxx96dmws=,tag:XEtppgBnCSgEfRMqQ6jTrQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
