app:
    alertmanager:
        env: ENC[AES256_GCM,data:X3Yy5WChYjG+pn8aw51A51w1m5YC/93vwRXjCgOnxBNe11L2gGUXyoySj90nuNEVAJQXssgH/2xCW3cWuSqrq7sfCKLFxBadE52CFWVko3lqT5ZQPkFl/1hWBjb7+o8=,iv:vDbQFywzallBfvT9U7QvQNN9/vUoM9AoGGxSvJahuiY=,tag:zDD08stnVvpYvxPSx2QeSw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNOS9DeWlXaTlUeTFkN1A5
            OEIxMHAxSno5QXFyZVczK0Q2ZENVbHBldmw0CnNHYWtHOFM0UHhUTSs5cDUvT1E2
            bVRhdUZ3SHMyLytWL3UvQ1R4Zzl0RFUKLS0tIEU5V3NrdmN0OTdnUGJlNEhwZW1s
            emxmcGU0TUw1eS9zVVM5eGxWR21ZTFkKi8j8MbxXRZ6jdvuJnk/guZroo9s6NoC4
            e8bajtW2dk8xI/0tlcfLTibFf5BbPg4kbMbpQIzLkKKDDcGYYAzXEQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age162k3jv9wyce4dkly60tu0l9jmme5qa3fmcrknrz6lx54ru2ftgaqcsy5e2
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxNFlnSmcrTlYxdXlRUmNl
            c1I1WVBpZ2RWVy94NUlmQzVwTVg2eUJXU2tJCjZZQXkzVVlOdTZyNit3bVdnbE9r
            UFBTVEhaUlQ4c2g1aXArRmh3TURaOGsKLS0tIGlqTFVYNW5LbGg4VVRzV2RWSzA4
            RU50MTBXcVhRRGtDLzJVaDlxTWZaRmsKZCg1r+yZCo5zoHy9a0za1UZrLDyn5lHv
            SYEo2cNsoifNwAaHEPVFgc754Fs4bbKorwIUwMhHpuZRCVpO93wrzg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ja28r58wftqjg6ps4vydx6wk5vyqpth8pwzpdcrk889e2hltseqx4af72
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPM0NOcUI0QVQ3Ny9aNjVB
            SW1Sb2taT2dxaHVMTlhaQXF0OEx6WDdidkQ0CmVGVW9SYjR4bWp6K1h2bTYwaU9Z
            L0MyNnlXR0tVK2phN2dZRWYwNXJSQjQKLS0tIHIvYk1BN2pBV2h6bmJpRFRQZDlx
            ZlR5UkNNNXhlLzhRS3YwOFFTSTF1bEUKA83a84yuY14fBYQAqQS+2LYYu1mYDTyf
            mDJaGW6wpEA3hckpaqoklNYSapOoYH/2JiV/QFRKVhR33/+Wj6PdSQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xuwlyavt70tt7rc0ufrwh7h907ymvg5mt7amxy0pygafmtm7eses2yj69x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSb05RRWNVR3MvNFM2azVG
            VEVnN3VYVUVjN2pSeUlpUXhrbGl1QjNwcjE4CjlHV2VFbTdPdlF5b1ZXWGJZcjdk
            ay9CczlTR0VlQ3EzT2M0YlovZ1JxYlEKLS0tIFo0c3FwOE40eGdVNCtHM1B1YkVu
            MW95U2xvbnpQL0toaWMzM041VVZPM2MKvvqV65n7QZaRBjQ8D8fhDvjRenHDntCd
            sCzpkIhTMssHHEEc1DkSuKHd5Awca0IaUKCI3YSzSB58vEodx8t83w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ued9ufgfwkrx00n3vmneae6grex4r0nuuytnwdk63u62flga4u5s9kd20j
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHZmswWFFNRCs2L00vb2ds
            S1UxMERoTEFuVTVVd21YUGNhQ0tvdTY1alRJCmxGYVoyV3orSElFY3M3NTIwVTNw
            TnhDVEExaWJEai9qcnZGcklJbDN3dHcKLS0tIEpYWWpmcEJXaTZ5blhVZDJoUC84
            Ti9SdW9lTXk3MmFTOWRWQzhaeENHOVEK2c3Mjy0CGb6w6ao6kijijpDJUBSiTWZ/
            gn8bAtpnxGuVPmOEcWkFzKMYHK53w6t8yg58+sy2crGk7S4UeFx0Rg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fsd8gpknmdtffnkq8an32zut24gf3h2vmglpaellh0j8fymrefvq25cjc5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4OHlCVDdRT2d0dzZRVjMz
            WklQK2ZjQmxZM1g5QTFmSERzZkI2cTJOVFhZClRxVEpheGlqb3F5OWlMZ3I5L1RG
            YnZCV1VBRHNNZktiSUtGbk13VFY1L1EKLS0tIDloVTlWTmc4bGgvckZheklpYitx
            WWlmNlpTUnhmYUVzc283VTNjc2JpQjgKKf+mXkGZGF4ckUZW2oh1iXvdZvXtEQPK
            koRrJG3SsyVRaX/cjqajspHoBkBLnZzbW07DZs0dNrBDjPlFIOu3lg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age122l7j4w7eyrd2gra4ft2jyndh4ec7j83s637e0fz7dhe45m369ds99tz44
    lastmodified: "2026-04-21T17:29:27Z"
    mac: ENC[AES256_GCM,data:LNnjLj6ghuE7HWQUGY/xA4IVMQEBxDzIkUfNADDVlOKc7Aqnl5h6AC6P5dLn3zlZGGsmLW2YEH+K3BSKMUfNwtRSlNYGJC4fMpscvowcj+jdrr0KRRjaIN0ifLUzjrj13SBG9cJ5cnrb9N2tU+vXjKX+t3p0OWc9nOP7IGiLLP8=,iv:CkWO+yauEOEFr1fjg/wkxxM97sls1Izbyaxxx96dmws=,tag:XEtppgBnCSgEfRMqQ6jTrQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
