# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "r8169"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/1db86dd7-21ee-4780-8b2f-f8d50beee2cb";
    fsType = "btrfs";
    options = ["subvol=root" "compress=zstd"];
  };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/3357ba6b-0595-47bf-9619-e271aa60987c";

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/1db86dd7-21ee-4780-8b2f-f8d50beee2cb";
    fsType = "btrfs";
    options = ["subvol=nix" "compress=zstd" "noatime"];
  };

  fileSystems."/persist" = {
    device = "/dev/disk/by-uuid/1db86dd7-21ee-4780-8b2f-f8d50beee2cb";
    fsType = "btrfs";
    options = ["subvol=persist" "compress=zstd"];
    neededForBoot = true;
  };

  fileSystems."/swap" = {
    device = "/dev/disk/by-uuid/1db86dd7-21ee-4780-8b2f-f8d50beee2cb";
    fsType = "btrfs";
    options = ["subvol=swap"];
  };

  fileSystems."/snapshots" = {
    device = "/dev/disk/by-uuid/1db86dd7-21ee-4780-8b2f-f8d50beee2cb";
    fsType = "btrfs";
    options = ["subvol=snapshots"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/E84E-F45A";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  swapDevices = [{device = "/swap/swapfile";}];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
