app:
    grafana:
        secret_key: ENC[AES256_GCM,data:STQv4q9ab+tqIdL91IjDX7IhuBrxXd1G6CeY8pGB1ItBwuj8EQvzFWoo6MDz273UPnA1U5HYWLHt0cq1XzzyfA==,iv:6dV9vj3LqQVInwMiV8KOau4bYE4ApLuLEw5XY1ahiac=,tag:eKOIqX8wzYs3B7MN7UydVg==,type:str]
        admin_password: ENC[AES256_GCM,data:B8GNxrzSXO/JK5uhc+JcAQ==,iv:r9p4k2omWGWpZ9OvmbSM3oIzggdHn46PMKIm8Pwb4Kw=,tag:jIgD6aoSP0RtsEkmXBdeZg==,type:str]
        client_secret: ENC[AES256_GCM,data:RprPI3Jz9C836BNJBGja7xnwUmTQOpZQryCKRFSFf+ssx5nEXACYOmlcUgs3MRcMoJ1s5h3DRMfT4IUbIcrfMQcR54/B9VkphSAO+2xAjvv8SpqlwauNlkTdJRSCPL+ukjgHBWoDEnhpgcIZICn73VvotoaQ+RHgqnALta0X/gk=,iv:2TeTtWRbtCNJcz8TBjTsX6JZdI8w/8vrMHoQz0bjv0g=,tag:9bBNNny53uRJqMsIJ2IiXQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtYTRHdnQ2cjhjbzlzNjJO
            S1NTdkdZdDZ1N3hHZlBldldIbEZnOFUveG1nCnBuNm04bmpENFdzZ25ZMDRySmxO
            aGZxTEYzc0xISHdUNVdRaEhMcitUVHcKLS0tIElBczA2TklJMnZubGpML0h1c28x
            c0YrL2piWFBwaUoxQ00yZllzK0J1TlUKuaWKaY89GY/o22+eeFZWgKSK4toyHbWf
            6JcHnWfzi6e79thbswEKzKCxbIpgu5Ro8Z7xWzaLUKLUSXleMevcsQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age162k3jv9wyce4dkly60tu0l9jmme5qa3fmcrknrz6lx54ru2ftgaqcsy5e2
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MFA2NlE2RU9neXEzQ0hM
            eHRrNStqb29vekl3aGtKVmtPUFZaM2pidWxzCnB5R2Z1b2w0Vk5nenlEcE44WkVR
            N2xlUHdxV2xXdWlxOFppcjhHUUVIbHcKLS0tIHl6S3BoUG5TL0pMU0MxN2ttUEdZ
            RFFhT2puQ0JwZjFUODdLZllXeHFOU2cK2iH4XQbQTUX3NfxEN2dIrxtRelM/4OG6
            JDh5hDQ0ortKSzgqRDjDJBkvC8by72imfwwo3tJKUv8sTT8bwstc8A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ja28r58wftqjg6ps4vydx6wk5vyqpth8pwzpdcrk889e2hltseqx4af72
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDRVBWVDhBTURoNm8yN0pa
            VW5GRHpOanRleFpOTVdEUHV1dDB4L2h1OGhrCis1WDd5VUt5MldhNDB1OUN6bzUv
            UmMvcDZqWURSR1krbktlalExTXJhTjQKLS0tIEUvT0JTTHlTbEZhMkNTdkROcjRH
            NmhzZTEyV3dMclpnb2pqOXJleFN4WG8Kassi5iNpkXELcdBzuUxe8xe/mcOAZRG1
            n1vLvBKBDTNJNOANupwB22Lo9ntjpMYHLhNgIgyM40MK7cJZT2o2jQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xuwlyavt70tt7rc0ufrwh7h907ymvg5mt7amxy0pygafmtm7eses2yj69x
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpek56Ti91eHlpNS9BcHZv
            dWozcm1QU25mcmZqNW1HUWxvN2I2bkVYUVhZCk9jZk9XaE1MbStyajFEK1dSbkg4
            V2U4QXE5aktiSUF4MWVoSHlnanBWWEUKLS0tIGhXWlRsNmUwaGExYVFrT2xwQVUz
            QSt4SEhCZDBuUmJiTVBYZVA0aGwvNE0KaT93uEtMit0u+UKKCJPLhNYHa3fHL/M/
            f9Nof0PmC8gP8Wv0G8qqr8A1CcgsIaKwzRGSUyTLMmryzCXUxF8kjA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ued9ufgfwkrx00n3vmneae6grex4r0nuuytnwdk63u62flga4u5s9kd20j
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQnBZOEl6c3BlSUtiaVN0
            V2lTeFA4Vktnam1zRXFpRFQ1ZFdQS1JjL0dJCkZYVXkzMk11ekdZbGV6c3I2cVVr
            R1pER0F6Y04ybVpJTE4xQnhpalFiMGcKLS0tIEI3TzdhbTRhczREZVZicUx6MUJL
            b2lialFzbG5RRHVaQm1VNDBrcUdjQUUKlaHZIa0dew1R8CLrFySb0BOf1YYYwVSL
            GAxe5tQx5gGd1AI5fLioWd6hOQMfOX+ccxL7sv/dDmXBtRJEH0IR5Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fsd8gpknmdtffnkq8an32zut24gf3h2vmglpaellh0j8fymrefvq25cjc5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMeUlNemh0bm1DSEllbnVD
            aWFReUtQSzd2S3h5eEp5elpodWc0UVNVMlNnCkphMHpGYW5FQzJsYzZWK1J3WTJ0
            TGNsejMrU09TeGtLZ3hDMXV0aE5UV2MKLS0tIGJvZktmWEI2MXgwWGtJT0ZlYUZC
            eDh1dkN0MWg4aU5YTEpVZ0k4RUo1L3cKLcCLVKerK+v01cWTWdIQTeNIEfpWTPgX
            TJkPnXKpCdwEhZ7wO0umbJja1ELgADj3wLvigIiRUvApykHg1abyuQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age122l7j4w7eyrd2gra4ft2jyndh4ec7j83s637e0fz7dhe45m369ds99tz44
    lastmodified: "2026-04-25T13:23:56Z"
    mac: ENC[AES256_GCM,data:B09l8dK0lVCfZ0LwuWWzMRxE2My2rG6tzR7OawJngaUr7SY7NooxVIIHnUJy5G3sEdHV6XKbadkRHcJ5cFWGcOGdYrXw98Xu4bljJ+bmOHVSJMRej40voYfzVuWsYDYn+JtbmfU/6XsI59t6L4Y5bKSg+7dVilcGpWBJUOa57zo=,iv:Xxh9GQpEKfeBlQMjFBD6DCMeIJFeYaNsLdtgYjNZA3s=,tag:jdiYb/dfrfmUwIxL4+hgcw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
