app:
    grafana:
        secret_key: ENC[AES256_GCM,data:STQv4q9ab+tqIdL91IjDX7IhuBrxXd1G6CeY8pGB1ItBwuj8EQvzFWoo6MDz273UPnA1U5HYWLHt0cq1XzzyfA==,iv:6dV9vj3LqQVInwMiV8KOau4bYE4ApLuLEw5XY1ahiac=,tag:eKOIqX8wzYs3B7MN7UydVg==,type:str]
        admin_password: ENC[AES256_GCM,data:B8GNxrzSXO/JK5uhc+JcAQ==,iv:r9p4k2omWGWpZ9OvmbSM3oIzggdHn46PMKIm8Pwb4Kw=,tag:jIgD6aoSP0RtsEkmXBdeZg==,type:str]
        client_secret: ENC[AES256_GCM,data:RprPI3Jz9C836BNJBGja7xnwUmTQOpZQryCKRFSFf+ssx5nEXACYOmlcUgs3MRcMoJ1s5h3DRMfT4IUbIcrfMQcR54/B9VkphSAO+2xAjvv8SpqlwauNlkTdJRSCPL+ukjgHBWoDEnhpgcIZICn73VvotoaQ+RHgqnALta0X/gk=,iv:2TeTtWRbtCNJcz8TBjTsX6JZdI8w/8vrMHoQz0bjv0g=,tag:9bBNNny53uRJqMsIJ2IiXQ==,type:str]
sops:
    age:
        - recipient: age162k3jv9wyce4dkly60tu0l9jmme5qa3fmcrknrz6lx54ru2ftgaqcsy5e2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBod0xkYWQ2Y3J2dWhQWWls
            aHR5WUQvUi9meE5sZGVwL2xEMkROVlhnbTBnCmNyT3hqV1ZZQ3JKdzh4YjRuOTNu
            aEgvWVZtUnJoY0VwQXgyV0NzZThCdE0KLS0tIEZtUnBuMFdCYXB4RUtFTUdYRjhI
            V1Z2a3c1blpjQlc5Y1NjWVJZU2RWU2cKEEFxp5f/I6k9u6ff7genGfW42d6JbqY3
            Pgk+1j9k41NQifT572WRsq1VDIBHXT0NBaLpU/9SrGE8I5UA5XK7iA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10ja28r58wftqjg6ps4vydx6wk5vyqpth8pwzpdcrk889e2hltseqx4af72
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0R0VRbjFuZEVwWUE5c3BC
            ZnFCQUFFZG1rNytnRitpelcxNXpsL0dycm5nCjdkaDdYZWhJMmdRRDc5YVk1V2RR
            U1MvM2pIcTFRcytSbkN1K0k5VWNwWlEKLS0tIGpFMWw0bVlZNEJoWlpOZW5hcWhT
            am8xWm90dVQrT0JRK1lqMzVHVzl6cEEKThseKlbWw9oEBFz51f0TfWSjCZBvrJyT
            aXyxuN9cjIOBRsG7eFzokh7tcdXbSUeKZPIZr7KxT8AetMngzEhf/Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xuwlyavt70tt7rc0ufrwh7h907ymvg5mt7amxy0pygafmtm7eses2yj69x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFdnlEWFIxUWxxdlJHbllP
            cW4weWJxemlhYWZIbVl2NVk0Q0JjYWhMVEZvCk16Q1hnWmNwYWQxVDcxamFTbFlE
            ZkIySHNXMmczZytrS0M4YVBsYjcxRUkKLS0tIFpVRERMQVFMRHd4ZiszREVTN2VL
            akZCM3N6c1R6em5XY3pMVldpV1BSVmsKuTaCNe/sCWPUmbEg/cnHtJ+zwqoplqEL
            6Zb3G1xx67IOKEnZ4yAW4Ljjs7yjEYtShy3DPW+M7zpltL+dD+NgDA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ued9ufgfwkrx00n3vmneae6grex4r0nuuytnwdk63u62flga4u5s9kd20j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZT0haTlNwRXN1dXdXRlFM
            NzNHZS9Sb09YVEs4d0JQZmRsOVhONDJiNUd3CjdaNDN5OUhUQkR6eVQ0Ti9KMTd4
            NHRlS0JsMFo2SitLTjdtQUdOZFM4MlkKLS0tIFJkOFdZRTUrb2hEcWZrdzVFMFA2
            bjR4S0lVNFJDYTd3L1kxKzlFbWJkVmcKuXUL5tJzNzc+HXgq4Gv26vrxtydTg3R7
            +rhTMQCUVsaebux4h9wYYtS831/51zQN5hlP7Sa3S/Hty8I5EjJP3w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1fsd8gpknmdtffnkq8an32zut24gf3h2vmglpaellh0j8fymrefvq25cjc5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVbWRMWmRDamVvb2xtSmN6
            OVZNTTFhNHdsOUNLZ3dJMWswV3ZxZnQvcGpVCjdpZzFpM2lTaGlEakZweG1qWURI
            RHV3K1Z2T013MWZTQnp3UlZJWnlkYVkKLS0tIHVZKzgyUWF1ZElsNlAxZ1BrL3hs
            QXhLUVRIek9mU051Yi8yM0ZJcmp6TG8KKXT8EsT+SlmdK8F1AgJDCGaWnAVaPX2V
            4DzkzPMzxWBbweq192sQwiL0VTVBk+JIZp4BNFKKlknvrc9ofRq2xg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T13:23:56Z"
    mac: ENC[AES256_GCM,data:B09l8dK0lVCfZ0LwuWWzMRxE2My2rG6tzR7OawJngaUr7SY7NooxVIIHnUJy5G3sEdHV6XKbadkRHcJ5cFWGcOGdYrXw98Xu4bljJ+bmOHVSJMRej40voYfzVuWsYDYn+JtbmfU/6XsI59t6L4Y5bKSg+7dVilcGpWBJUOa57zo=,iv:Xxh9GQpEKfeBlQMjFBD6DCMeIJFeYaNsLdtgYjNZA3s=,tag:jdiYb/dfrfmUwIxL4+hgcw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
